
apiVersion: v1

kind: Namespace

metadata: 

  name: homework

---

apiVersion: v1

kind: Secret

metadata:

  name: regcred

  namespace: homework

data:

  .dockerconfigjson: XXXX

type: kubernetes.io/dockerconfigjson

---

apiVersion: v1

kind: Service

metadata: 

  name: net1

  namespace: homework

spec: 

  sessionAffinity: None

  type: NodePort

  selector: 

    app: app

  ports:

    - port: 3000

      targetPort: 3000

      protocol: TCP

      name: testname

      nodePort: 31234

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: dep1

  namespace: homework

spec:

  replicas: 1

  selector:

    matchLabels:

      app: app

  template:

    metadata:

      labels:

        app: app

    spec:

      containers:

        - name: cont

          image: a65084c4c8/tpt:ver1 #bkimminich/juice-shop

          imagePullPolicy: Always #IfNotPresent

          ports:

            - name: port

              containerPort: 3000

              protocol: TCP

      imagePullSecrets:

            - name: regcred