apiVersion: v1

kind: Service

metadata: 

  name: net1

  namespace: homework

spec: 

  sessionAffinity: None

  type: NodePort

  selector: 

    app: app

  ports:

    - port: 3000

      targetPort: 3000

      protocol: TCP

      name: portName1

      nodePort: 30010